### PR TITLE
Fix #7 and fix #6

### LINKED ISSUE #6: Can't find module @angular/Http
Hello! It looks like the package is using an older version of the HTTP client. Here's the exact message:

`ERROR in node_modules/ngx-embed-video/dist/src/embed-video.service.d.ts(1,22): error TS2307: Cannot find module '@angular/http'.`

I think that needs to be updated to `HttpClient`, but I'm not totally sure. I'm going to try to hack at it for now but if you have a chance to take a look I'd really appreciated it!

Matt

### LINKED ISSUE #7: Doesn't work with Typescript 2.6.2 or higher / Angular Package Format
I'll get this
```
ERROR in ./node_modules/ngx-embed-video/index.ts
Module build failed: Error: ..../node_modules/ngx-embed-video/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/...../node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:677:23)
    at plugin.done.then (...../node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
ERROR in ./node_modules/ngx-embed-video/src/embed-video.service.ts
Module build failed: Error:..../node_modules/ngx-embed-video/src/embed-video.service.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
**The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).**
    at AngularCompilerPlugin.getCompiledFile (/...../node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:677:23)
    at plugin.done.then (....../node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

### PR DESCRIPTION
**Pull request by sixtoad**

### CODE REVIEW

**Comment by sixtoad** [comment]
#7

**Comment by SamirHodzic** [comment]
@sixtoad thanks for PR, not sure that `ng-packagr` will work with current structure. Will review & test it soon when I catch time.

**Comment by codyayers** [comment]
@SamirHodzic, could you review this and get it merged so we can use this?

**Comment by SamirHodzic** [comment]
@codyayers will do this weekend, didn't have time before. Need to check that we won't break it totally.

**Comment by codyayers** [comment]
It did unfortunately, so more work will be required I’m afraid

**Comment by sixtoad** [comment]
@codyayers, I checked the component and it was working for me, how did it break the component?, maybe it was the second commit that changes the http library to make the request (I did not check with an example)

**Comment by chris-now** [comment]
Any ETA on this?

**Comment by sixtoad** [comment]
@SamirHodzic, it needs some changes for Angular 6, but we should have a version that can run on angular 5 before, do you have an estimation when you can review this?
Thanks :)

**Comment by SamirHodzic** [comment]
Sorry, should be fixed by https://github.com/SamirHodzic/ngx-embed-video/pull/16, but seems like we are skipping Angular 5 with this.
